version: 2
jobs:
  build:
    docker:
      - image: framgiaciteam/laravel-workspace:7.3
    steps:
      - checkout
      - run:
          name: Copying .env file
          command: |
            cp .env.example .env

      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run:
          name: Installing vendor package
          command: |
            composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # run
      - run:
          name: Generating app key
          command: |
            php artisan key:generate
      - run:
          name: Running test
          command: |
            composer test
      - run:
          name: Sending notification
          when: on_fail
          command: |
            if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: $CHATWORK_TOKEN" -d \
                "body=[info][title]Build $CIRCLE_BUILD_NUM - FAIL[/title]
                Repo: $CIRCLE_PROJECT_REPONAME
                Author: $CIRCLE_USERNAME
                Branch: $CIRCLE_BRANCH
                Build link: https://circleci.com/gh/dqhuy78/hbot/$CIRCLE_BUILD_NUM
                [/info]" \
                "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM_ID/messages"
            fi
      - run:
          name: Sending notification
          when: on_success
          command: |
            if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: $CHATWORK_TOKEN" -d \
                "body=[To:2611547]
                [info][title]Build $CIRCLE_BUILD_NUM - SUCCESS[/title]
                Repo: $CIRCLE_PROJECT_REPONAME
                Author: $CIRCLE_USERNAME
                Branch: $CIRCLE_BRANCH
                Build link: https://circleci.com/gh/dqhuy78/hbot/$CIRCLE_BUILD_NUM
                [/info]" \
                "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM_ID/messages"
            fi
  #Run deploy to Heroku
  deploy-heroku:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git config --global push.default current
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git -f
      - run:
          name: Sending notification
          when: on_fail
          command: |
            if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: $CHATWORK_TOKEN" -d \
                "body=[info][title]Deploy build $CIRCLE_BUILD_NUM - FAIL[/title]
                Repo: $CIRCLE_PROJECT_REPONAME
                Author: $CIRCLE_USERNAME
                Branch: $CIRCLE_BRANCH
                Build link: https://circleci.com/gh/dqhuy78/hbot/$CIRCLE_BUILD_NUM
                [/info]" \
                "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM_ID/messages"
            fi
      - run:
          name: Sending notification
          when: on_success
          command: |
            if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: $CHATWORK_TOKEN" -d \
                "body=[To:2611547]
                [info][title]Deploy build $CIRCLE_BUILD_NUM - SUCCESS[/title]
                Repo: $CIRCLE_PROJECT_REPONAME
                Author: $CIRCLE_USERNAME
                Branch: $CIRCLE_BRANCH
                Build link: https://circleci.com/gh/dqhuy78/hbot/$CIRCLE_BUILD_NUM
                [/info]" \
                "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM_ID/messages"
            fi
  #Run deploy to digital ocean server
  deploy-vps:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy to Digital Ocean
          command: |
            ssh $SSH_USER@$SSH_HOST "./hbot-deploy.sh"

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy-heroku:
          requires:
            - build
          filters:
            branches:
              only:
                - master
